version: '3'
services:

 app2:
    build: ./warrepo
    ports:
    - "8889:8080"
    depends_on:
    - db
 db:
    build: ./postgresql
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    container_name: db

volumes:
    db_data:


